apiVersion: v1
kind: Service
metadata:
  name: service-test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31567
      name: node-test
  selector:
    type: deployment
