apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    tier: backend-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 2
  template:
    metadata:
      name: portgres-app
      labels:
        app: postgres
        tier: backend
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust