apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
    tier: backend-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 2
  template:
    metadata:
      name: redis-app
      labels:
        app: redis
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379