apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-deployment
  labels:
    app: result
    tier: frontend-deployment
spec:
  selector:
    matchLabels:
      app: result
  replicas: 4
  template:
    metadata:
      name: results-app
      labels:
        app: result
        tier: frontend
    spec:
      containers:
        - name: results
          image: kodekloud/examplevotingapp_result:v1