apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
  labels:
    app: pod-configmap
    tier: test
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: config-test