apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app: secret-app
    tier: testing
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: secret
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: PASSWORD
        - name: w
          value: w